# Generated by Django 3.0.3 on 2020-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0002_auto_20200611_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item_detail',
            old_name='item_name',
            new_name='Category',
        ),
        migrations.RemoveField(
            model_name='item_detail',
            name='dryclean_price',
        ),
        migrations.RemoveField(
            model_name='item_detail',
            name='washing_price',
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Dryclean_price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Item_name',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='item_detail',
            name='Washing_price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
