# Generated by Django 3.0.3 on 2020-06-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0003_auto_20200611_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default=' ', max_length=255)),
                ('lastName', models.CharField(default=' ', max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
