# Generated by Django 3.0.3 on 2020-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0005_auto_20200618_2031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogory_name',
            new_name='Catogary_name',
        ),
    ]
