# Generated by Django 3.0.3 on 2020-06-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0008_auto_20200619_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=' ', max_length=50)),
                ('Service_Available', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
