# Generated by Django 3.0.3 on 2020-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0012_auto_20200622_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=50)),
                ('Password', models.CharField(default='', max_length=50)),
                ('CPassword', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
