# Generated by Django 3.0.3 on 2020-06-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0013_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registeration',
        ),
    ]
