# Generated by Django 3.0.3 on 2020-07-12 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0015_auto_20200711_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='client',
            new_name='person',
        ),
    ]
