# Generated by Django 3.0.3 on 2020-07-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0016_auto_20200712_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
    ]
