# Generated by Django 3.0.3 on 2020-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0018_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRUD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentId', models.CharField(max_length=50)),
                ('StudentName', models.CharField(max_length=50)),
                ('StudentPhone', models.CharField(max_length=50)),
                ('DateTime', models.DateField()),
            ],
        ),
    ]
