# Generated by Django 3.0.3 on 2020-07-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0019_crud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='DateTime',
            new_name='Birthday',
        ),
    ]
