# Generated by Django 3.0.3 on 2020-07-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry_app', '0020_auto_20200716_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='StudentId',
            new_name='Id',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='StudentName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='StudentPhone',
            new_name='Phone',
        ),
        migrations.AlterField(
            model_name='crud',
            name='Birthday',
            field=models.DateField(blank=True),
        ),
    ]
